export default[{
    id:0,
    venueName:"Pearl Event Venue",
    image:"/body-image-new.jpg",
    map:"https://goo.gl/maps/fi4EnfsKWfvcc7bt8",
    location:"Chabahil,Kathmandu",
    contactName:"Sridhar Karki",
    contactNumber: "9841376543",
},{
    id:1,
    venueName:"Khowpa Event Venue",
    image:'/body-image-new.jpg',
    map:"https://googl/maps/9ZiNCMw81jU8bx5i7",
    location:"Kalimati",
    contactName:"Basanta Tuladhar",
    contactNumber:"9850347821",
},{
    id:2,
    venueName:"Danphe Event Venue",
    image:"/body-image-new.jpg",
    map:"https://goo.gl/maps/9ZiNCMw81jU8bx5i7",
    location:"Kalimati,Kathmandu",
    contactName:"Basanta Tuladhar",
    contactNumber:"9850347821",
},{
    id:3,
    venueName:"Danphe Event Venue",
    image:'/body-image-new.jpg',
    map:"https://goo.gl/maps/9ZiNCMw81jU8bx5i7",
    location:"Kalimati",
    contactName:"Basanta Tuladhar",
    contactNumber:"9850347821",
},{
    id:4,
    venueName:"Danphe Event Venue",
    image:'/body-image-new.jpg',
    map:"https://goo.gl/maps/9ZiNCMw81jU8bx5i7",
    location:"Kapan",
    contactName:"Basanta Tuladhar",
    contactNumber:"9850347821",
},{
    id:5,
    venueName:"Pearl Event Venue",
    image:'/body-image-new.jpg',
    map:"https://goo.gl/maps/9ZiNCMw81jU8bx5i7",
    location:"Charkhal",
    contactName:"Basanta Tuladhar",
    contactNumber:"9850347821",
},{
    id:6,
    venueName:"Danphe Event Venue",
    image:'/body-image-two.jpg',
    map:"https://goo.gl/maps/9ZiNCMw81jU8bx5i7",
    location:"Kalimati",
    contactName:"Basanta Tuladhar",
    contactNumber:"9850347821",
},{
    id:7,
    venueName:"Danphe Event Venue",
    image:'/body-image-two.jpg',
    map:"https://goo.gl/maps/9ZiNCMw81jU8bx5i7",
    location:"Kalimati",
    contactName:"Basanta Tuladhar",
    contactNumber:"9850347821",
}]